# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.IntegerField(choices=[(12, '12 Meses'), (24, '24 Meses'), (36, '36 Meses'), (48, '48 Meses'), (60, '60 Meses')])),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('hitch', models.DecimalField(decimal_places=2, max_digits=2)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
