# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotient', '0002_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hitch',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
