# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotient', '0003_auto_20170620_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='hitch',
            field=models.IntegerField(),
        ),
    ]
