# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotient', '0004_auto_20170620_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField(verbose_name='Año')),
                ('package', models.CharField(max_length=100, verbose_name='Paquete')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name_plural': 'Opciones de los carros',
                'verbose_name': 'Opciones del carro',
                'default_permissions': ('add', 'change', 'delete', 'show', 'list'),
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'default_permissions': ('add', 'change', 'delete', 'show', 'list'), 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'default_permissions': ('add', 'change', 'delete', 'show', 'list'), 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'default_permissions': ('add', 'change', 'delete', 'show', 'list'), 'verbose_name': 'Plan de financiamiento', 'verbose_name_plural': 'Planes de financiamiento'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='version',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.IntegerField(choices=[(1, 'Crédito automotriz'), (2, 'Arrendamiento Puro')], default=1, verbose_name='Tipo de crédito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotient.Brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Comisión por apertura'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hitch',
            field=models.IntegerField(verbose_name='Enganche'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Tasa de interés'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='time',
            field=models.IntegerField(choices=[(12, '12 Meses'), (24, '24 Meses'), (36, '36 Meses'), (48, '48 Meses'), (60, '60 Meses')], verbose_name='Tiempo'),
        ),
        migrations.AddField(
            model_name='caroption',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotient.Car', verbose_name='Carro'),
        ),
    ]
