# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotient', '0006_auto_20170713_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.IntegerField(choices=[(1, 'Autos'), (2, 'SUV'), (3, 'Pickups'), (4, 'Vans'), (5, 'Deportivos'), (6, 'Eléctricos')], default=1, verbose_name='Tipo de carro'),
            preserve_default=False,
        ),
    ]
