# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotient', '0007_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroption',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción del paquete'),
            preserve_default=False,
        ),
    ]
